### ISSUE TITLE
Screenshot for your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [Menrui/v-trimming-gui#1]
Hi!
Your Python program has something most do not.... a GUI

![image](https://user-images.githubusercontent.com/46163555/150795518-f5d7cb23-e65e-47b2-96ac-8473ced4f2be.png)

Your repos's visitors would likely enjoy seeing what your program creates by posting a screenshot in your readme.  Since it's a program that operates on videos and is also highly interactive, it may be even better if your image was a GIF.

You can use GitHub issues to store your image files and then paste a reference to them in your readme.md file.    You'll find a couple of techniques discussed in the Py SimpleGUI Cookbook:
https://pysimplegui.readthedocs.io/en/latest/cookbook/#recipe-post-your-screen-shots-please

I hope you enjoyed using PySimpleGUI.

![image](https://user-images.githubusercontent.com/46163555/150795563-b0a47af3-845d-48fa-b48b-437b5b591429.png)

**Comment by TechStudent10** [comment]
I totally support this. I saw that you (PySimpleGUI) starred this and it looked interesting, but I didn't see any screenshots.

**Comment by PySimpleGUI** [comment]
Wow!  I had no idea anyone could see what I star.  

As I work on the "Online Gallery" feature, I'm adding to the feature list - return the string that can be pasted into a readme or other markdown document to embed the screenshot.  If not there, then the gallery itself will have instructions on embedding the images found there into a readme.

**Comment by TechStudent10** [comment]
I totally DID NOT expect a reply, but thank you.

> Wow! I had no idea anyone could see what I star.

Yeah, your stars are public.

![image](https://user-images.githubusercontent.com/76978184/150810051-4141925a-0ea7-4fb1-9ad1-7831726e7262.png)

Every time you star something, about all of your 4.7k followers will get it in their "Recent Activity" section. This doesn't trigger push notifications as far as I know.

![image](https://user-images.githubusercontent.com/76978184/150810329-f68791f3-1c4e-4be2-bd93-48614d8b86e9.png)

> As I work on the "Online Gallery" feature, I'm adding to the feature list - return the string that can be pasted into a readme or other markdown document to embed the screenshot. If not there, then the gallery itself will have instructions on embedding the images found there into a readme.

That's an awesome feature!

**Comment by Menrui** [comment]
Hi. Thanks for your comments.
I've added a screenshot to the Readme.md.

> You can use GitHub issues to store your image files and then paste a reference to them in your readme.md file. You'll find a couple of techniques discussed in the Py SimpleGUI Cookbook:
https://pysimplegui.readthedocs.io/en/latest/cookbook/#recipe-post-your-screen-shots-please
This was very useful information. Thank you!

**Comment by PySimpleGUI** [comment]
Nice!  
Thank you!  They look great!

If you are ever looking for a screen recorder that makes GIFs that are TINY, then try ShareX.  It makes all of the moving images in my readmes and docs and they're TINY so that they load very quickly.  You'll find a number of them in my readme.  HTTP://www.PySimpleGUI.com

This one for example is only 4.6 MB.  They're often under 1 MB

![](https://raw.githubusercontent.com/PySimpleGUI/PySimpleGUI/master/images/for_readme/YOLO_GIF.gif)
